### ISSUE TITLE
Visualization needed for the given dataset

### ISSUE THREAD

**Issue by josh-weebs** [josh-weebs/Fireadora#3]
In this section, the user can use the pre-existing dataset to perform various visualization techniques. Through which the user can can select multiple columns to plot/visualize where the user can also perform tasks like displaying heatmap, plotting various graphs (mainly Pairplot, Countplot, boxplot)

**Comment by Brianrmendes** [comment]
I would like to take up the issue!

**Comment by josh-weebs** [comment]
Great! You can start adding visualization one by one and merge them as you go, so that we both stay on track with the development process of the project!

**Comment by Brianrmendes** [comment]
Okay that works!

**Comment by arunsamuel4560** [comment]
I would like to work as well on this issue

**Comment by alenjohn0571** [comment]
The 3 of us intend to solve this issue together as a group

**Comment by josh-weebs** [comment]
Okay that sounds great, so the 3 of you can work on it together.

And if there are any queries, feel free to ask

**Comment by Brianrmendes** [comment]
Our group has solved the issue that was requested, kindly check it and revert if any changes are required :)

**Comment by josh-weebs** [comment]
Sorry for the delay, was busy with some work. This is exactly what I wanted . Thank you for your contribution.
